---
title: "IgAVN_tesis_2026"
author: "Benjamin"
format: html
editor: visual
---

## Paquetes

```{r}
# Instalar 'pacman' si no se encuentra (gestor de paquetes)
if (!require("pacman")) install.packages("pacman")

# Cargar los paquetes necesarios para el análisis
pacman::p_load(tidyverse, tableone, survival, survminer, gtsummary,flextable,ggsurvfit, pheatmap)


# tidiverse: para manipulación de datos (dplyr) y gráficos (ggplot2)
# tableone: para crear tablas descriptivas (Tabla 1)
# survival: el motor para el análisis de supervivencia
# survminer: para visualizar curvas de Kaplan-Meier con ggplot2
# gtsummary: crea tablas de resumen estadístico
# flextable: Sirve para crear, formatear y exportar tablas  personalizadas a Word
# pheatmap: es para hacer el análisis jerarquico
```

## Datos

```{r}
datos <- readr::read_csv("IgAVN_datos_limpios_abril_2026.csv")

# Explorción inicial para ver que se necesita arrgelar
# glimpse(datos)
# summary(datos)
```

## Definir el tipo de variable

```{r}

variables_categoricas <- c(
  "hospital", 
  "sexo", 
  "diabetes", 
  "hipertension", 
  "dislipidemia", 
  "obesidad", 
  "enf_autoinmune",
  "enf_tiroidea",
  "cirrosis",
  "manifestacion_cutanea", 
  "manifestacion_gastro", 
  "manifestacion_articular", 
  "sx_glomerular", 
  "tfg_menor_60",
  "leucocituria", 
  "eritrocituria",
  "if_igm",
  "if_igg",
  "if_iga",
  "if_c3",
  "if_c1q",
  "if_kappa",
  "if_lambda",
  "medias_lunas",
  "medias_lunas_tipo",
  "vasos_afectados",
  "mat", 
  "oxford_M",
  "oxford_E",
  "oxford_S",
  "oxford_T",
  "oxford_C", 
  "biopsia_piel", 
  "prednisona", 
  "plasmaferesis", 
  "ciclofosfamida",
  "metilprednisolona",
  "rituximab", 
  "mantenimiento",
  "isglt2",
  "recaida_renal",
  "recaida_extrarenal",
  "remplazo_renal",
  "perdida_tfg30",
  "duplicar_cr",
  "erct", 
  "muerte",
  "desenlace_agrupado"
  )

variables_numericas <- c(
  "edad_a_biopsia",
  "peso",
  "talla",
  "imc",
  "tas",
  "tad",
  "cr",
  "ckd_epi",
  "bun",
  "c3",
  "c4",
  "pcr",
  "vsg",
  "albumina",
  "volumen_u",
  "prot_U24hrs",
  "cr_U24hrs",
  "ipc",
  "hemoglobina",
  "plaquetas",
  "numero_glomerulos",
  "esclerosis_global",
  "esclerosis_global_porcent",
  "esclerosis_segmentaria",
  "esclerosis_segmentaria_porcent",
  "fibrosis_intersiticial",
  "atrofia_tubular",
  "infiltrado_inflamatorio",
  "medias_lunas_numero",
  "ciclofosfamida_acumulada",
  "recaida_renal_numero",
  "cr_nadir_primer_ano"
  )

varibales_fecha <- c(
  "fecha_biopsia",
  "fecha_nacimiento",
  "fecha_sintomas",
  "fecha_ultimo_seguimiento",
  "fecha_recaida",
  "fecha_recaida_extrarenal",
  "fecha_inicio_trr",
  "fecha_perdida_tfg",
  "fecha_duplicar_cr",
  "fecha_erct",
  "fecha_muerte",
  "fecha_cr_nadir",
  "fecha_desenlace"
  )


datos_limpios <- datos %>% 
        mutate_at(vars(variables_categoricas), as.factor) %>% 
        mutate_at(vars(variables_numericas), as.double) %>% 
        mutate_at(vars(all_of(varibales_fecha)), ymd) 

```

## Tiempo entre 2 fechas

```{r}
cols_fechas <- c("fecha_nacimiento", "fecha_sintomas","fecha_recaida", "fecha_recaida_extrarenal", "fecha_perdida_tfg", 
                 "fecha_inicio_trr", "fecha_erct", "fecha_muerte",
                 "fecha_ultimo_seguimiento", "fecha_desenlace")


datos_limpios_2 <- datos_limpios %>% 
  mutate(across(
    .cols = all_of(cols_fechas),
    .fns = ~ floor(time_length(interval(fecha_biopsia, .x), "month")),
    .names = "tiempo_{.col}"
  )) %>% 
  mutate(
    tiempo_fecha_nacimiento = floor(abs(tiempo_fecha_nacimiento)/12),
    tiempo_fecha_sintomas = abs(tiempo_fecha_sintomas)
  )

```

## Crear variable de RIESGO

```{r}
# 




```

## Tabla de características clínicas

```{r}
#Etiquetas a las variables
labels_list <- list(
  sexo ~ "Sexo (%)",
  edad_a_biopsia ~ "Edad en biopsia (años)",
  diabetes ~ "Diabetes (%)",
  hipertension ~ "Hipertensión (%)",
  dislipidemia ~ "Dislipidemia (%)",
  obesidad ~ "Obesidad (%)",
  enf_autoinmune ~ "Enfermedad autoinmune (%)",
  peso ~ "Peso (kg)",
  talla ~ "Talla (m)",
  imc ~ "IMC (kg/m²)",
  tas ~ "Presión arterial sistólica (mmHg)",
  tad ~ "Presión arterial diastólica (mmHg)",
  manifestacion_cutanea ~ "Manifestación cutánea (%)",
  manifestacion_gastro ~ "Manifestación gastrointestinal (%)",
  manifestacion_articular ~ "Manifestación articular (%)",
  sx_glomerular ~ "Síndrome glomerular",
  ckd_epi ~ "TFGe por CKD-EPI (mL/min/1.73m²)",
  prednisona ~ "Prednisona (%)",
  plasmaferesis ~ "Plasmaféresis (%)",
  ciclofosfamida ~ "Ciclofosfamida (%)",
  metilprednisolona ~ "Metilprednisolona (%)",
  rituximab ~ "Rituximab (%)",
  mantenimiento ~ "Tratamiento de mantenimiento",
  isglt2 ~ "iSGLT2 (%)",
  recaida_renal ~ "Pacientes con recaída renal (%)",
  recaida_extrarenal ~ "Pacientes con recaída extrarenal (%)",
  perdida_tfg30 ~ "Perdida de TFG 30%",
  remplazo_renal ~ "Pacientes con terapia de remplazo renal (%)",
  erct ~ "Pacientes con ERCT (%)",
  muerte ~ "Defunción (%)"
)


Tabla_1 <- datos_limpios %>%
  # Seleccionar variables
  select(
    sexo, edad_a_biopsia, diabetes, hipertension, dislipidemia, obesidad,
    enf_autoinmune, peso, talla, imc, tas, tad, manifestacion_cutanea,
    manifestacion_gastro, manifestacion_articular, sx_glomerular, ckd_epi,
    prednisona, plasmaferesis, ciclofosfamida, metilprednisolona, rituximab,
    mantenimiento, isglt2, recaida_renal, recaida_extrarenal, 
    perdida_tfg30, remplazo_renal, erct, muerte, desenlace_agrupado
    ) %>%
  tbl_summary(
    by = "desenlace_agrupado",
    missing = "ifany",
    label = labels_list
  ) %>%
  add_overall(col_label = "**Todos**, N = {N}") %>%
  add_p() %>% 
  modify_header(label = "**Variable**") %>%
  modify_caption("Tabla 1.- Características basales") %>%
  bold_labels()


# Visualizar la tabla
Tabla_1

# Exportar a Word
Tabla_1 %>% as_flex_table() %>% flextable::save_as_docx(path = "Tabla_1.docx")
```

## Tabla de laboratorios

```{r}
# Etiquetar a las variables
label_list_laboratorios <- list(
      cr = "Creatinina",
      bun = "BUN",
      c3 = "C3",
      c4 = "C4",
      pcr = "PCR",
      vsg = "VSG",
      albumina = "Albúmina",
      prot_U24hrs = "Proteínas en orina de 24 hrs",
      ipc = "IPC",
      leucocituria = "Leucocituria",
      eritrocituria = "Eritrocituria",
      hemoglobina = "Hemoglobina",
      plaquetas = "Plaquetas"
)

# Para usar names es necesario poner etiquetas con "="
variables_tabla_labs <- names(label_list_laboratorios)

Tabla_2 <- datos_limpios %>% 
  select(all_of(variables_tabla_labs), desenlace_agrupado) %>% 
  tbl_summary(
    by = "desenlace_agrupado",
    missing = "ifany",
    label = label_list_laboratorios
  ) %>% 
  add_overall(col_label = "**Todos**, N = {N}") %>%
  add_p() %>% 
  modify_header(label = "**Variable**") %>%
  modify_caption("Tabla 2.- Características de laboratorio") %>%
  bold_labels()

# Visualizar la tabla
Tabla_2

# Exportar a Word
Tabla_2 %>% as_flex_table() %>% flextable::save_as_docx(path = "Tabla_2.docx")
```

## Tabla de biopsias

```{r}
label_list_histologia <- list(
  numero_glomerulos = "Número de glomérulos",
  esclerosis_global = "Esclerosis global",
  esclerosis_global_porcent = "Esclerosis global (%)",
  esclerosis_segmentaria = "Esclerosis segmentaria",
  esclerosis_segmentaria_porcent = "Esclerosis segmentaria (%)",
  fibrosis_intersiticial = "Fibrosis intersticial (%)", 
  atrofia_tubular = "Atrofia tubular (%)",
  infiltrado_inflamatorio = "Infiltrado inflamatorio (%)",
  if_igm = "IgM",
  if_igg = "IgG",
  if_iga = "IgA",
  if_c3 = "C3",
  if_c1q = "C1q",
  if_kappa = "Kappa",
  if_lambda = "Lambda",
  medias_lunas = "Medias lunas",
  medias_lunas_numero = "Número de medias lunas",
  medias_lunas_tipo = "Tipo de medias lunas",
  vasos_afectados = "Vasos afectados",
  mat = "Microangiopatía trombótica",
  oxford_M = "Oxford M",
  oxford_E = "Oxford E",
  oxford_S = "Oxford S",
  oxford_T = "Oxford T",
  oxford_C = "Oxford C"
)

# --- 2. Crear la Tabla (tbl_summary) ---

Tabla_3 <- datos_limpios %>% 
  select(names(label_list_histologia), desenlace_agrupado) %>%
  tbl_summary(
    by = "desenlace_agrupado",
    label = label_list_histologia,     
    missing = "ifany",
    missing_text = "(Valores perdidos)" 
  ) %>%
  add_overall(col_label = "**Todos**, N = {N}") %>%
  add_p() %>% 
  modify_header(label = "**Variable**") %>%
  modify_caption("Tabla 3.- Características histopatológicas") %>%
  bold_labels()


Tabla_3

Tabla_3 %>% as_flex_table() %>% flextable::save_as_docx(path = "Tabla_3.docx")

```

## Fenotipos

```{r}

# ==============================================================================
# CLUSTERING JERÁRQUICO: INTENTO 2 (Sin sexo, con Oxford C)
# ==============================================================================

# 1. Cargar librerías (si no están cargadas)
library(tidyverse)
library(pheatmap)

# 2. Seleccionar SOLO las 5 variables de interés (Combo: Función + Glomérulo + Túbulo)
# Asegúrate de que "oxford_C" esté escrito exactamente igual que en tu base
datos_cluster <- datos_limpios %>%
  select(ckd_epi, ipc, oxford_C, fibrosis_intersiticial, infiltrado_inflamatorio)

# 3. Limpieza y Preprocesamiento

# A. Tratamiento de Oxford C (IMPORTANTE)
# Para que el clustering funcione, Oxford C debe ser numérico (0, 1, 2).
datos_cluster$oxford_C <- as.numeric(datos_cluster$oxford_C)

# B. Quitar filas con datos faltantes (NA)
datos_cluster <- na.omit(datos_cluster)

# C. ESCALAR LOS DATOS (Z-scores)
datos_escalados <- scale(datos_cluster)

# Verificamos que todo sea numérico y luzca bien
head(datos_escalados)

# 4. Generar el Heatmap Visual
pheatmap(datos_escalados,
         scale = "none",             
         clustering_distance_rows = "euclidean",
         clustering_method = "ward.D2",
         cutree_rows = 4,            # Mantenemos 3 cortes para ver qué sale
         show_rownames = FALSE,      
         main = "Fenotipos NVIgA")

# ==============================================================================
# EXTRACCIÓN DE LOS FENOTIPOS
# ==============================================================================

# 1. Calcular distancias y árbol
dist_mat <- dist(datos_escalados, method = "euclidean")
hclust_avg <- hclust(dist_mat, method = "ward.D2")

# 2. Cortar el árbol en 3 grupos
grupos_pacientes <- cutree(hclust_avg, k = 4)

# 3. Asignar el fenotipo a los pacientes
datos_cluster_final <- datos_cluster %>%
  mutate(Fenotipo = as.factor(grupos_pacientes))

# Conteo rápido: ¿Cuántos quedaron en cada grupo?
table(datos_cluster_final$Fenotipo)

# ==============================================================================
# TABLA DE CARACTERIZACIÓN (TABLA 1 SIMULADA)
# ==============================================================================

datos_cluster_final %>%
  group_by(Fenotipo) %>%
  summarise(
    n = n(),
    Media_TFGe = mean(ckd_epi),
    Media_Proteinuria = mean(ipc),
    Media_Semilunas_C = mean(oxford_C),  # Aquí veremos qué grupo es el "Activo"
    Media_Fibrosis = mean(fibrosis_intersiticial),
    Media_Infiltrado = mean(infiltrado_inflamatorio)
  )
```

```{r}
datos_fenotipos_3 <- datos_limpios_2 %>%
  # Convertimos las sospechosas a número
  mutate(
    oxford_C = as.numeric(as.character(oxford_C)),
    ckd_epi = as.numeric(as.character(ckd_epi)),
    prot_U24hrs = as.numeric(as.character(prot_U24hrs))
  ) %>%
  select(registro, hospital, prot_U24hrs, ckd_epi, oxford_C, 
         desenlace_agrupado, tiempo_fecha_desenlace, edad_a_biopsia) %>%
  filter(ckd_epi < 80, prot_U24hrs > 2.5)
```
